import type { Metadata } from "next";
import { fontTitulo, fontCuerpo } from "./fonts";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      suppressHydrationWarning
      className={`${fontTitulo.variable} ${fontCuerpo.variable}`}
    >
      <body className={` antialiased`}>
        <noscript>Página realizada por Jhan Gómez P. @jhangmez.</noscript>
        {children}
      </body>
    </html>
  );
}
