import type { Metadata } from "next";
import { fontTitulo, fontCuerpo } from "./fonts";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      suppressHydrationWarning
      className={`${fontTitulo.variable} ${fontCuerpo.variable}`}
    >
      <head>
        <meta charSet="UTF-8" />
        <meta name="description" content="ApuDataIT" />
        <link
          rel="icon"
          type="image/svg+xml"
          href="/favicon.ico"
          sizes="128x128"
        />
      </head>
      <body
        className={`bg-background text-foreground font-cuerpo selection:bg-[#304bd1] selection:text-primary-foreground antialiased`}
      >
        <noscript>Página realizada por Jhan Gómez P. @jhangmez.</noscript>
        <Toaster />
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}
